import { ImageSourcePropType } from "react-native";
export interface UserLocation {
  address?: string;
  city?: string;
  state?: string;
  country?: string;
  zipCode?: string;
  lastUpdated?: string;
  coordinates?: {
    type?: string;
    coordinates?: number[]; // [longitude, latitude]
  };
}

export interface SavedAddress {
  _id?: string;
  label: "Home" | "Work" | "Other";
  address: string;
  city: string;
  state: string;
  country: string;
  zipCode?: string;
  coordinates: {
    latitude: number;
    longitude: number;
  };
  isDefault: boolean;
  createdAt?: Date | string;
}

export interface User {
  // Identifiers
  id?: string; // Derived from _id for convenience across app
  _id?: string; // MongoDB ID from backend

  // Core profile
  firstName: string;
  lastName?: string;
  email?: string;
  phoneNumber?: string; // Preferred
  phone?: string; // Backward compatibility
  role?: string;
  profilePicture?: string | { uri: string }; // S3 key or local URI
  profilePictureUrl?: string; // CloudFront URL (generated by backend)

  // Location
  // Backend returns an object; we also provide a derived string
  location?: UserLocation;
  locationText?: string;

  // Stats & meta
  rating?: number; // Aggregated rating shown on profile
  averageEmployeeRating?: number | null;
  averageEmployerRating?: number | null;
  completionRate?: number;
  totalJobs?: number;
  totalReviews?: number;
  isVerified?: boolean;
  isActive?: boolean;
  isProfileComplete?: boolean;
  isSuspended?: boolean;
  blockedUsers?: string[];
  lastLogin?: string | null;
  createdAt?: string;
  updatedAt?: string;

  // Preferences from backend
  preferences?: {
    locationBasedSearch?: boolean;
    searchRadius?: number;
  };

  // Notification settings
  notificationSettings?: {
    verificationCodes?: boolean;
    jobUpdates?: boolean;
    applicationStatus?: boolean;
    messages?: boolean;
    systemUpdates?: boolean;
  };

  // Bank account details
  bankAccount?: {
    accountHolderName?: string;
    accountNumber?: string;
    ifscCode?: string;
    bankName?: string;
    accountType?: "savings" | "current";
    isVerified?: boolean;
    verifiedAt?: string | null;
  };

  // Saved addresses for quick location selection
  savedAddresses?: SavedAddress[];
}

export interface EditProfileParams {
  user: User;
}

export interface ProfileScreenProps {
  navigation: any;
  route: any;
}

export interface EditProfileScreenProps {
  navigation: any;
  route: {
    params: EditProfileParams;
  };
}

export interface Review {
  id: string;
  reviewerName: string;
  reviewerImage: ImageSourcePropType;
  date: string;
  rating: number;
  comment: string;
}

// Job Post Types
export interface JobCategory {
  _id: string;
  name: string;
}

export interface JobLocation {
  address: string;
  city?: string;
  coordinates?: {
    type?: string;
    coordinates: number[]; // [longitude, latitude]
  };
  country: string;
  state?: string;
  zipCode?: string;
}

export interface JobUser {
  _id?: string;
  firstName: string;
  id: string;
  lastName: string;
  phoneNumber: string;
  profilePicture?: string;
}

export interface JobPost {
  __v: number;
  _id: string;
  address: string;
  applicantCount: number;
  assignedUsers: any[];
  budget: number;
  category: JobCategory;
  createdAt: string;
  description: string;
  isCompletedByWorker: boolean;
  isFlexible: boolean;
  isMultiVacancy: boolean;
  isOpen?: boolean;
  isPaymentDone: boolean;
  isRemote: boolean;
  isVerifiedByEmployer: boolean;
  jobStatus: string;
  location: JobLocation;
  name: string;
  participantsNumber: number;
  photos: string[];
  requirements: string[];
  status: string;
  timePreference: string[];
  fromTime?: string; // HH:MM format for non-flexible jobs
  toTime?: string; // HH:MM format for non-flexible jobs
  onDate?: string; // ISO date string — the actual scheduled work date (from backend `onDate` field)
  updatedAt: string;
  userId: JobUser;
  requiresVerification?: boolean;
  applicants?: any[];
  hasApplied?: boolean;
  // Server-computed per-user fields (set by backend in getJobPostings)
  isEmployer?: boolean;       // true if the current user is the job owner/employer
  isAssignedWorker?: boolean; // true if the current user is an accepted/assigned worker
  // Arrival state (derived from worker's session in the job list response)
  hasArrived?: boolean;    // true if this worker has already pressed 'I Have Reached'
  arrivalStatus?: 'pending' | 'arrived' | 'verified'; // mirrors JobSession.arrivalStatus
}

// For backward compatibility and convenience
export interface JobCardData {
  _id: string;
  name: string;
  budget: number;
  applicantCount: number;
  location: JobLocation;
  createdAt: string;
  status: string;
  jobStatus?: string; // Backend job status
  category: JobCategory;
  description: string;
  isRemote: boolean;
  isFlexible: boolean;
  requirements: string[];
  timePreference: string[];
  fromTime?: string; // HH:MM format for non-flexible jobs
  toTime?: string; // HH:MM format for non-flexible jobs
  userId: JobUser;
  isCompletedByWorker?: boolean; // Backend flag for worker completion
  isVerifiedByEmployer?: boolean; // Backend flag for employer verification
  isPaymentDone?: boolean; // Backend flag for payment completion
}
