import { StyleSheet } from "react-native";
import DeviceDimensions from "../../../constants/DeviceDimenions";
import { ThemeColors } from "../../../constants/Colors";

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scrollContent: {
      flexGrow: 1,
      alignItems: "center",
      paddingHorizontal: 24,
      paddingTop: 40,
    },
    headerContainer: {
      alignItems: "center",
      marginBottom: 40,
      width: "100%",
    },
    title: {
      fontSize: 32,
      fontFamily: "bold",
      color: colors.black,
      marginBottom: 12,
      textAlign: "center",
      lineHeight: 40,
    },
    subtitle: {
      fontSize: 16,
      lineHeight: 24,
      textAlign: "center",
      fontFamily: "regular",
      color: colors.grey,
      maxWidth: "80%",
    },
    image: {
      width: 300 * DeviceDimensions.widthRatio,
      height: 250 * DeviceDimensions.heightRatio,
      marginTop: 40,
      marginBottom: 20,
      resizeMode: "contain",
    },
    formContainer: {
      width: "100%",
      marginBottom: 30,
    },
    inputLabel: {
      fontSize: 14,
      fontFamily: "medium",
      color: colors.black,
      marginBottom: 8,
      marginLeft: 4,
    },
    inputWrapper: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.white,
      borderRadius: 16,
      height: 56,
      paddingHorizontal: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: "transparent",
    },
    inputWrapperFocused: {
      borderColor: colors.primary,
    },
    countryCode: {
      fontSize: 16,
      fontFamily: "medium",
      color: colors.black,
      marginRight: 12,
      paddingRight: 12,
      borderRightWidth: 1,
      borderRightColor: colors.addressGrey,
    },
    input: {
      flex: 1,
      fontSize: 16,
      fontFamily: "regular",
      color: colors.black,
      height: "100%",
    },
    button: {
      backgroundColor: colors.primary,
      width: "100%",
      height: 56,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
      marginTop: 24,
    },
    buttonDisabled: {
      backgroundColor: colors.grey,
      shadowOpacity: 0,
      elevation: 0,
    },
    buttonText: {
      color: colors.white,
      fontSize: 18,
      fontFamily: "bold",
    },
    footer: {
      flexDirection: "row",
      marginTop: "auto",
      marginBottom: 30,
      alignItems: "center",
    },
    footerText: {
      fontSize: 14,
      color: colors.grey,
      fontFamily: "regular",
      textAlign: "center",
    },
    createAccount: {
      fontSize: 14,
      color: colors.blue,
      fontFamily: "bold",
      marginLeft: 4,
    },
    subtitleOtp: {
      fontSize: 16,
      lineHeight: 24,
      textAlign: "center",
      fontFamily: "regular",
      color: colors.grey,
      marginTop: 20,
      marginBottom: 40,
      paddingHorizontal: 16,
    },
  });
