import { StyleSheet } from "react-native";
import DeviceDimensions from "../../../constants/DeviceDimenions";
import { Colors } from "../../../constants/Colors";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  profileCard: {
    backgroundColor: Colors.white,
    borderRadius: 24,
    marginHorizontal: 16,
    marginTop: 12 * DeviceDimensions.heightRatio,
    padding: 20,
    alignItems: "center",
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: "rgba(79, 70, 229, 0.1)", // Primary with low opacity
  },
  profileImage: {
    width: 110,
    height: 110,
    borderRadius: 55,
    marginBottom: 12,
    borderWidth: 3,
    borderColor: Colors.primary,
  },
  name: {
    fontSize: 22,
    fontWeight: "700",
    marginTop: 8,
    marginBottom: 4,
    color: Colors.black,
    letterSpacing: 0.5,
  },
  locationContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    backgroundColor: Colors.categoryBox,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  locationText: {
    fontSize: 14,
    color: Colors.primary,
    fontWeight: "600",
    marginLeft: 4,
  },
  statsContainer: {
    flexDirection: "row",
    width: "100%",
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#F0F0F0",
    paddingTop: 20,
  },
  statBox: {
    flex: 1,
    alignItems: "center",
  },
  statLabel: {
    fontSize: 11,
    color: "#888",
    marginBottom: 6,
    fontWeight: "600",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  statNumber: {
    fontSize: 22,
    fontWeight: "800",
    color: Colors.primary,
  },
  statSubLabel: {
    fontSize: 11,
    color: "#666",
    marginTop: 4,
    fontWeight: "500",
  },
  completionRateContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  infoIcon: {
    marginLeft: 4,
  },
  separator: {
    width: 1,
    backgroundColor: "#E0E0E0",
    height: "100%",
    alignSelf: "center",
  },
  dropdown: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    marginHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  dropdownText: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.black,
  },
  dropdownDetail: {
    fontSize: 14,
    color: "#555",
    marginBottom: 8,
  },
  reviewContainer: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginTop: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  reviewerInfo: {
    flexDirection: "row",
    marginBottom: 12,
  },
  reviewerImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  reviewerNameContainer: {
    flex: 1,
    justifyContent: "center",
    marginLeft: 12,
  },
  reviewerName: {
    fontWeight: "700",
    fontSize: 16,
    marginBottom: 2,
    color: Colors.black,
  },
  stars: {
    flexDirection: "row",
  },
  starIcon: {
    marginRight: 2,
  },
  reviewDate: {
    fontSize: 12,
    color: "#888",
    alignSelf: "flex-start",
    marginTop: 4,
  },
  reviewText: {
    fontSize: 14,
    lineHeight: 22,
    color: "#444",
  },
  seeAllButton: {
    backgroundColor: Colors.categoryBox, // Light primary
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 30,
  },
  seeAllText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: "700",
  },
  experienceContainer: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
    overflow: "hidden",
  },
  dropdownHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dropdownTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.black,
  },
  dropdownContent: {
    paddingTop: 12,
    overflow: "hidden",
  },
  imageRow: {
    marginTop: 12,
    marginBottom: 6,
  },
  imagePlaceholder: {
    width: 92 * DeviceDimensions.widthRatio,
    height: 67 * DeviceDimensions.heightRatio,
    backgroundColor: "#F5F5F5",
    borderRadius: 8,
    marginRight: 8,
  },
  buttonContainer: {
    paddingHorizontal: 16,
    marginTop: 20,
  },
  fixedBottomContainer: {
    position: "absolute",
    bottom: 200,
    left: 0,
    right: 0,
    zIndex: 10,
  },
  bankDetailsCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    marginHorizontal: 16,
    marginTop: 16,
    padding: 20,
    shadowColor: Colors.primary,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  bankDetailsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  bankDetailsHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  bankDetailsTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.black,
  },
  editIconButton: {
    padding: 8,
    borderRadius: 10,
    backgroundColor: Colors.categoryBox,
  },
  bankDetailsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F5F5F5",
  },
  bankDetailsLabel: {
    fontSize: 14,
    color: Colors.grey,
    fontWeight: "500",
  },
  bankDetailsValue: {
    fontSize: 15,
    color: Colors.black,
    fontWeight: "600",
    flex: 1,
    textAlign: "right",
    marginLeft: 16,
  },
  editBankButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 16,
    paddingVertical: 12,
    gap: 8,
    backgroundColor: Colors.categoryBox,
    borderRadius: 12,
  },
  editBankButtonText: {
    fontSize: 15,
    color: Colors.primary,
    fontWeight: "700",
  },
  addBankCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    marginHorizontal: 16,
    marginTop: 16,
    padding: 24,
    alignItems: "center",
    shadowColor: Colors.primary,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(79, 70, 229, 0.1)",
  },
  addBankTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.black,
    marginTop: 16,
    marginBottom: 8,
  },
  addBankText: {
    fontSize: 14,
    color: Colors.grey,
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 20,
  },
  addBankButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 12,
    shadowColor: Colors.primary,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  addBankButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: "700",
  },
});

export default styles;
