import { StyleSheet } from "react-native";
import DeviceDimensions from "../../../constants/DeviceDimenions";
import { Colors } from "../../../constants/Colors";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
    padding: 16,
  },
  scrollContainer: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  locationHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  locationSelector: {
    flexDirection: "row",
    alignItems: "center",
  },
  locationTitle: {
    fontSize: 16,
    fontFamily: "bold",
    color: Colors.black,
    marginRight: 4 * DeviceDimensions.widthRatio,
  },
  locationSubtitle: {
    fontSize: 12,
    fontFamily: "regular",
    color: Colors.grey,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8E8E8",
    borderRadius: 12,
    width: "100%",
    height: 50 * DeviceDimensions.heightRatio,
    marginTop: 16 * DeviceDimensions.heightRatio,
    paddingHorizontal: 12,
  },
  searchIcon: {
    marginRight: 10 * DeviceDimensions.widthRatio,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: "regular",
    color: Colors.black,
  },
  bannerContainer: {
    borderRadius: 16,
    marginTop: 8,
    marginBottom: 16 * DeviceDimensions.heightRatio,
    flexDirection: "row",
    height: 140.21 * DeviceDimensions.heightRatio,
    width: "100%",
  },
  banner: {
    width: "100%",
    height: "100%",
  },
  bannerTextContainer: {
    flex: 3,
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  bannerTitle: {
    fontSize: 20,
    fontFamily: "bold",
    color: Colors.white,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  bannerSubtitle: {
    fontSize: 14,
    fontFamily: "regular",
    color: Colors.white,
    marginTop: 4 * DeviceDimensions.heightRatio,
    opacity: 0.9,
  },
  postNowButton: {
    backgroundColor: Colors.white,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    alignSelf: "flex-start",
    marginTop: 16 * DeviceDimensions.heightRatio,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  postNowText: {
    color: Colors.primary,
    fontSize: 12,
    fontFamily: "bold",
  },
  bannerImage: {
    flex: 2,
    height: "100%",
  },
  filtersScrollContainer: {
    backgroundColor: Colors.background,
    paddingVertical: 10,
    marginBottom: 4,
  },
  stickyFilterContainer: {
    backgroundColor: Colors.background,
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: Colors.grey + "10",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 4,
  },
  filtersContainer: {
    alignItems: "center",
  },
  filterButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.white,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.addressGrey,
    paddingHorizontal: 14 * DeviceDimensions.widthRatio,
    paddingVertical: 8 * DeviceDimensions.heightRatio,
    marginRight: 10 * DeviceDimensions.widthRatio,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  filterText: {
    fontSize: 13,
    fontFamily: "medium",
    color: Colors.black,
    marginRight: 4 * DeviceDimensions.widthRatio,
  },
  jobCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 16 * DeviceDimensions.widthRatio,
    marginBottom: 16 * DeviceDimensions.heightRatio,
    shadowColor: Colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    width: "100%",
    borderLeftWidth: 5,
    borderLeftColor: Colors.primary,
  },
  jobCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14 * DeviceDimensions.heightRatio,
  },
  categoryContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.categoryBox,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  avatarContainer: {
    width: 20 * DeviceDimensions.widthRatio,
    height: 20 * DeviceDimensions.widthRatio,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 6 * DeviceDimensions.widthRatio,
  },
  categoryText: {
    fontSize: 12,
    fontFamily: "bold",
    color: Colors.primary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  priceText: {
    fontSize: 18,
    fontFamily: "bold",
    color: Colors.primary,
  },
  jobTitle: {
    fontSize: 17,
    fontFamily: "bold",
    color: Colors.black,
    marginBottom: 12 * DeviceDimensions.heightRatio,
    flex: 1,
    marginRight: 8,
    lineHeight: 22,
  },
  jobDetailsContainer: {
    flexDirection: "row",
    marginBottom: 16 * DeviceDimensions.heightRatio,
    flexWrap: "wrap",
    gap: 12,
  },
  titleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12 * DeviceDimensions.heightRatio,
    width: "100%",
  },
  locationContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F8F8",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  locationText: {
    fontSize: 13,
    fontFamily: "medium",
    color: Colors.grey,
    marginLeft: 4 * DeviceDimensions.widthRatio,
  },
  jobFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#F5F5F5",
  },
  vacanciesContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.background,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 6,
  },
  vacanciesText: {
    fontSize: 12,
    fontFamily: "medium",
    color: Colors.primary,
  },
  timeAgoText: {
    fontSize: 12,
    fontFamily: "medium",
    color: Colors.grey,
  },
  statusContainer: {
    backgroundColor: Colors.tabGrey,
    paddingHorizontal: 12 * DeviceDimensions.widthRatio,
    height: 24,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  statusText: {
    fontSize: 11,
    fontFamily: "bold",
    color: Colors.black,
    textTransform: "uppercase",
  },

  // Distance Text Style (add to job card)
  distanceText: {
    fontSize: 11,
    color: Colors.grey,
    marginTop: 2,
    fontWeight: "600",
    textAlign: 'right',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: Colors.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '75%',
    paddingTop: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: Colors.addressGrey,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: Colors.black,
  },
  modalOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: Colors.addressGrey,
  },
  selectedOption: {
    backgroundColor: Colors.categoryBox + "40", // 40% opacity
  },
  modalOptionText: {
    fontSize: 16,
    color: Colors.black,
    fontWeight: '500',
  },
  selectedOptionText: {
    color: Colors.primary,
    fontWeight: 'bold',
  },

  // Active filters styles
  activeFiltersContainer: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: Colors.white,
    marginHorizontal: 16,
    borderRadius: 12,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: Colors.addressGrey,
  },
  activeFiltersTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.primary,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  activeFiltersRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  activeFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.primary,
    marginBottom: 4,
  },
  activeFilterText: {
    fontSize: 12,
    color: Colors.primary,
    marginRight: 4,
  },

  // Results and pagination styles
  resultsContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  resultsText: {
    fontSize: 14,
    color: Colors.grey,
    fontWeight: '500',
  },
  loadMoreContainer: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  loadMoreButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  loadMoreText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
  },
  endOfResultsContainer: {
    alignItems: 'center',
    paddingVertical: 16,
  },
  endOfResultsText: {
    fontSize: 14,
    color: Colors.grey,
    fontStyle: 'italic',
  },

});


export default styles;