import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const createStyles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: colors.black,
    },
    listContainer: {
      padding: 16,
      paddingBottom: 100,
    },
    card: {
      backgroundColor: colors.white,
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 5,
      borderWidth: 1,
      borderColor: colors.border,
    },
    selectedCard: {
      borderColor: colors.primary,
      backgroundColor: colors.primary + "10",
    },
    cardHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    profileImage: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: colors.border,
    },
    profileInfo: {
      flex: 1,
      marginLeft: 12,
    },
    name: {
      fontSize: 18,
      fontWeight: "600",
      color: colors.black,
      marginBottom: 4,
    },
    ratingContainer: {
      flexDirection: "row",
      alignItems: "center",
    },
    ratingText: {
      marginLeft: 4,
      fontSize: 14,
      color: colors.grey,
      fontWeight: "500",
    },
    rateContainer: {
      backgroundColor: colors.primary + "20",
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    rateText: {
      color: colors.primary,
      fontWeight: "700",
      fontSize: 14,
    },
    description: {
      fontSize: 14,
      color: colors.grey,
      lineHeight: 20,
      marginBottom: 12,
    },
    detailsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    detailItem: {
      flexDirection: "row",
      alignItems: "center",
    },
    detailText: {
      marginLeft: 6,
      fontSize: 13,
      color: colors.grey,
    },
    selectionIndicator: {
      position: "absolute",
      top: 12,
      right: 12,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 100,
      paddingHorizontal: 40,
    },
    emptyText: {
      fontSize: 18,
      fontWeight: "600",
      color: colors.black,
      marginTop: 16,
      textAlign: "center",
    },
    emptySubtext: {
      fontSize: 14,
      color: colors.grey,
      marginTop: 8,
      textAlign: "center",
    },
    bottomActions: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.white,
      padding: 20,
      paddingBottom: 34,
      flexDirection: "row",
      justifyContent: "space-between",
      borderTopWidth: 1,
      borderTopColor: colors.border,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 20,
    },
    rejectButton: {
      flex: 1,
      height: 54,
      backgroundColor: "#FF3B30",
      borderRadius: 14,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 10,
    },
    acceptButton: {
      flex: 2,
      height: 54,
      backgroundColor: colors.primary,
      borderRadius: 14,
      justifyContent: "center",
      alignItems: "center",
    },
    buttonText: {
      color: "#FFF",
      fontSize: 16,
      fontWeight: "700",
    },
    selectionCount: {
      backgroundColor: colors.primary,
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 12,
      marginBottom: 12,
      alignSelf: "center",
    },
    selectionCountText: {
      color: "#FFF",
      fontSize: 12,
      fontWeight: "600",
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
  });
